/**
 * Simple Loan API
 * This is a loan API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Lien } from './lien';
import { Person } from './person';


export class Loan { 
   public loanNumber: string;
   public loanAmount: number;
   public loanManagementFees: number;
   public loanTerm: string;
   public originationDate: Date;
   public originationAccount: string;
   public lien: Lien;
   public borrower:Person
   public status: string;
   constructor (loanNumber: string, loanAmount: number, loanManagementFees: number, loanTerm: string, originationDate: Date, originationAccount: string, lien: Lien, borrower:Person, status: string) {
       this.loanNumber = loanNumber;
       this.loanAmount = loanAmount;
       this.loanManagementFees = loanManagementFees;
       this.loanTerm = loanTerm;
       this.originationDate = originationDate;
       this.originationAccount =originationAccount;
       this.lien = lien;
       this.borrower = borrower;
       this.status = status;
   }
}
